name: sliver_head_automatic_adsorption
description: "This is a custom sliver component that can automatically attach to the top"
version: 1.0.4
repository: https://github.com/7-bit-zhang/sliver_head_automatic_adsorption
issue_tracker: https://github.com/7-bit-zhang/sliver_head_automatic_adsorption/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

